build_job:
    script:
        - cabal update
        - cabal sandbox init
        - cabal install --enable-tests --enable-coverage --disable-optimization
        - make pebble
        - cabal test
        - cat dist/hpc/vanilla/html/crag-integration/hpc_index.html

