build_job:
    script:
        - cabal update
        - cabal sandbox init
        - cabal install --enable-tests --enable-coverage
        - cabal test acme-unit
        - cat dist/hpc/vanilla/html/acme-unit/hpc_index.html

